sudo: required

services:
  - docker

before_install:
  - docker build -t jimexist/sqoop .
  - docker run -d --name sqoop jimexist/sqoop
  - echo "sleep 30 seconds and wait for container to run" && sleep 30

script:
  - docker run --rm --link sqoop --volume $(pwd):/tmp/test --entrypoint sqoop2-shell jimexist/sqoop /tmp/test/test_script.sqoop
